---
jobs:
  test:
    steps:
      - name: Download SCA-Bom-Detect
        run: curl -s https://download.scantist.io/sca-bom-detect-v4.5.jar --output
          sca-bom-detect-v4.5.jar
      - name: Upload to {{companyConfig.APP_NAME}}
        env:
          DEVSECOPS_TOKEN: ${{secrets.PENTEST }}
          DEVSECOPS_IMPORT_URL: https://api-app.scantist.io/v2/scans/ci-scan/
        run: whoami && id
